import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navigation/Navbar'
import Home from './Home'

const App: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
    </div>
  )
}

export default App
