import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navigation/Navbar'
import styles from '../styles/Home.module.css'
import LatestFrom from '../components/LatestFrom'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className='container'>
        HERE IS SOME CONTENT 
        <div className={styles.homePage}>
          <LatestFrom blog='memberingMari' />
          <LatestFrom blog='anxiousToAdventurous' />
          <LatestFrom blog='myWalkingShoes' />
        </div>
      </div>
    </div>
  )
}

export default Home
