import Head from 'next/head'

import Navbar from '../components/Navigation/Navbar'
import DisplayPost from '../components/DisplayPost'
import styles from '../styles/BlogPage.module.css'

export async function getServerSideProps() {
  const response = await fetch('https://public-api.wordpress.com/rest/v1.1/sites/micaelasmusingsca.wordpress.com/posts/?category=%27membering%20Mari');
  const data = await response.json();
  return {
    props: { 
      posts: data.posts,
    }
  }
}

interface post {
  ID: number;
  URL: string;
  attachment_count: number;
  attachments: object;
  author: object;
  capabilities: object;
  categories: object;
  content: string;
  date: string;
  discussion: object;
  excerpt: string;
  featured_image: string;
  format: string;
  geo: boolean;
  global_ID: string;
  guid: string;
  i_like: boolean;
  is_following: boolean;
  is_reblogged: boolean;
  like_count: number;
  likes_enabled: boolean
  menu_order: number;
  meta: object;
  metadata: Array<object>;
  modified: string;
  other_URLs: object;
  page_template: string;
  parent: boolean;
  password: string;
  post_thumbnail: object;
  publicize_URLs: Array<string>;
  sharing_enabled: boolean;
  short_URL: string;
  site_ID: number;
  slug: string;
  status: string;
  sticky: boolean;
  tags: object;
  terms: object;
  title: string;
  type: string;
}

type props = {
  posts: Array<post>
};

const MemberingMari = (props: props) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div  className='container'>
        <div className={styles.preambleText}>
          <p>This is the space I have created for myself and just so happened to share it with you! In this series I will muse over memories of my little sister. Through the stories, memories, and grief that I will chat about on here, I hope you laugh, cry, and most of all, never forget the beautiful soul we lost.</p>
          <p>Huge thank you to my beautiful Aunty Mer who has so graciously edited every one of the posts below and aided me in the process of forming these words in a way that helps you feel the feelings inside my soul.</p>
          <p>Enjoy!</p>
          {props.posts.map((post) => (
            <DisplayPost key={post.ID} title={post.title} blurb={post.excerpt} slug={post.slug} />
          ))}
        </div>
      </div>
    </div>
  )
}

export default MemberingMari;
