import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navigation/Navbar'
import styles from '../styles/BlogPage.module.css'
import { getMemberingMariPosts } from './api'

const MemberingMari: NextPage = () => {
  const posts = getMemberingMariPosts();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div  className='container'>
        <div className={styles.preambleText}>
          <p>This is the space I have created for myself and just so happened to share it with you! In this series I will muse over memories of my little sister. Through the stories, memories, and grief that I will chat about on here, I hope you laugh, cry, and most of all, never forget the beautiful soul we lost.</p>
          <p>Huge thank you to my beautiful Aunty Mer who has so graciously edited every one of the posts below and aided me in the process of forming these words in a way that helps you feel the feelings inside my soul.</p>
          <p>Enjoy!</p>
        </div>
        {posts}
      </div>
    </div>
  )
}

export default MemberingMari;
