import type { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navigation/Navbar'
import styles from '../styles/BlogPage.module.css'
import { getMyWalkingShoesPosts } from './api'

const MyWalkingShoes: NextPage = () => {
  const posts = getMyWalkingShoesPosts();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div  className='container'>
        <div className={styles.preambleText}>
          <p>Welcome to the newest addition to my blog! Playing off the saying “walk a mile in their shoes”, My Walking Shoes is where I will be giving you insight into what it might be like to walk a mile in my shoes. Here I delve into the nitty gritty of my thoughts and adventures. I will open up about my opinions and my plans to spend a lot of time outside. I hope you stay a while and get the opportunity to walk a mile in My Walking Shoes.</p>
        </div>
        {posts}
      </div>
    </div>
  )
}

export default MyWalkingShoes;
